language: ruby
cache:
  directories:
    - .bundle
before_install:
  - bundle install --path .bundle
rvm:
  - 2.1
  - 2.2
  - jruby-9.0.0.0
branches:
  only:
    - master
script: "bundle exec rake spec rspec"
